# Generated by Django 4.1.5 on 2023-01-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        ("type", "0001_initial"),
        ("docs", "0002_alter_doc_card_alter_doc_store_alter_doc_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="store",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.store"
            ),
        ),
        migrations.AlterField(
            model_name="doc",
            name="type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="type.type"
            ),
        ),
    ]
