# Generated by Django 4.1.5 on 2023-01-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        ("docs", "0005_alter_doc_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc",
                to="store.store",
            ),
        ),
    ]
